const path = require('path');

const buildMockEesNumber = (fileName) => {
  const parsed = path.parse(fileName || 'document.pdf');
  const normalizedName = parsed.name
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 32);

  return `OCR-${normalizedName || 'PDF'}-${Date.now()}`;
};

const analyzePdf = async ({ fileName, checksum }) => {
  const eesNumber = buildMockEesNumber(fileName);

  return {
    provider: 'MOCK',
    confidence: 0.72,
    extractedAt: new Date().toISOString(),
    payload: {
      eesNumber,
      bulletinNumber: `SB-TRIAL-${checksum.slice(0, 8).toUpperCase()}`,
      evaluations: [
        {
          itemNo: '1',
          paragraph: 'OCR Trial',
          requirementDesc: 'Temporary OCR extraction result. Replace this mock result with the real AI OCR response when the integration is ready.',
          taskType: 'Record Review',
          reference: fileName || 'Uploaded PDF',
          isApplicable: true,
          adRelated: 'TO BE REVIEWED',
          isWarranty: false,
          affectedEsn: [],
          isRepetitive: false,
          dueAt: 'TO BE REVIEWED',
          remarks: 'Generated by mock OCR adapter for backend flow testing.'
        }
      ]
    }
  };
};

module.exports = {
  analyzePdf
};
